"""compress bulk raw payloads

Revision ID: 50d3359a86d5
Revises: ec425df1c592
Create Date: 2026-08-27 03:22:33.896861

Adds gzip storage for oversized raw payloads and backfills the ones already
written. See ADR-0010: YouTube's feeds return no cache validators, so every
nightly poll stores ~64 KB of near-identical XML per channel.

The autogenerated draft was wrong in two ways, both fixed here:
  * `codec` NOT NULL with no server default fails against existing rows.
  * The downgrade restored `payload` NOT NULL without decompressing first, so it
    would fail on exactly the rows this migration creates.
"""

from __future__ import annotations

import gzip
import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from nh.db.types import JSONVariant

revision: str = "50d3359a86d5"
down_revision: str | None = "ec425df1c592"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

COMPRESS_OVER = 4_096
BATCH = 500


def _as_text(value: object) -> str:
    """Stored JSON comes back as TEXT on SQLite and as a dict on Postgres."""
    return (
        value if isinstance(value, str) else json.dumps(value, separators=(",", ":"), default=str)
    )


def upgrade() -> None:
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payload_gz", sa.LargeBinary(), nullable=True))
        batch_op.add_column(
            sa.Column("codec", sa.String(length=8), nullable=False, server_default="json")
        )
        batch_op.alter_column("payload", existing_type=JSONVariant, nullable=True)
        batch_op.create_index("ix_raw_records_prune", ["kind", "at"], unique=False)

    # Backfill: compress payloads already stored that exceed the threshold.
    bind = op.get_bind()
    while True:
        rows = bind.execute(
            sa.text(
                "SELECT id, payload FROM raw_records "
                "WHERE codec = 'json' AND payload IS NOT NULL "
                "AND length(payload) > :n LIMIT :lim"
            ),
            {"n": COMPRESS_OVER, "lim": BATCH},
        ).fetchall()
        if not rows:
            break
        for row_id, payload in rows:
            bind.execute(
                sa.text(
                    "UPDATE raw_records SET payload = NULL, payload_gz = :gz, codec = 'gzip' "
                    "WHERE id = :id"
                ),
                {"gz": gzip.compress(_as_text(payload).encode(), compresslevel=6), "id": row_id},
            )


def downgrade() -> None:
    # Decompress first: the column cannot go back to NOT NULL while the rows this
    # migration created still hold their payload in payload_gz.
    bind = op.get_bind()
    while True:
        rows = bind.execute(
            sa.text("SELECT id, payload_gz FROM raw_records WHERE codec = 'gzip' LIMIT :lim"),
            {"lim": BATCH},
        ).fetchall()
        if not rows:
            break
        for row_id, blob in rows:
            bind.execute(
                sa.text(
                    "UPDATE raw_records SET payload = :p, payload_gz = NULL, codec = 'json' "
                    "WHERE id = :id"
                ),
                {"p": gzip.decompress(blob).decode(), "id": row_id},
            )

    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_records_prune")
        batch_op.alter_column("payload", existing_type=JSONVariant, nullable=False)
        batch_op.drop_column("codec")
        batch_op.drop_column("payload_gz")
