"""seed geo and primary sources, term stratum, scorecard stage

Slice 5, all additive.

`seed_terms.stratum` joins the unique key so one Wikipedia article can serve both
the topic and event strata while sharing its `demand_snapshots` rows — the two
strata are carried in parallel and arbitrated by Gate E (ADR-0022).
`niche_seeds.primary_sources` holds dated research rather than a scored metric
(ADR-0020). `scorecards.stage_confidence` and `.detail` carry the basis for a
stage so a later shift is attributable (ADR-0023).

Revision ID: 9776d98d63ef
Revises: aa2d2317759c
Create Date: 2026-08-27 18:47:17.021826

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nh.db.types import JSONVariant

revision: str = "9776d98d63ef"
down_revision: str | None = "aa2d2317759c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("niche_seeds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("primary_sources", JSONVariant, nullable=True))

    with op.batch_alter_table("scorecards", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stage_confidence", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("detail", JSONVariant, nullable=True))

    with op.batch_alter_table("seed_terms", schema=None) as batch_op:
        # server_default: the column is NOT NULL and 20 rows already exist. Every
        # term curated before Slice 5 is a topic-level article by definition.
        batch_op.add_column(
            sa.Column("stratum", sa.String(length=16), nullable=False, server_default="topic")
        )
        batch_op.drop_constraint(batch_op.f("uq_seed_terms_term"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_seed_terms_term", ["seed_id", "source", "term", "stratum"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seed_terms", schema=None) as batch_op:
        batch_op.drop_constraint("uq_seed_terms_term", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_seed_terms_term"), ["seed_id", "source", "term"]
        )
        batch_op.drop_column("stratum")

    with op.batch_alter_table("scorecards", schema=None) as batch_op:
        batch_op.drop_column("detail")
        batch_op.drop_column("stage_confidence")

    with op.batch_alter_table("niche_seeds", schema=None) as batch_op:
        batch_op.drop_column("primary_sources")

    # ### end Alembic commands ###
