"""videos.description

Descriptions are ~20x the text a title carries and are the input the relevance
scorer needs. For videos already collected they exist only inside `raw_records`,
which `nh prune` deletes at `raw_retention_days` — see ADR-0017 and
`nh backfill descriptions`.

Revision ID: 97de0ad3e0a9
Revises: d55acea8b47f
Create Date: 2026-08-27 16:51:12.025329

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97de0ad3e0a9"
down_revision: str | None = "d55acea8b47f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops the column, and with it the only durable copy of the descriptions.

    Reversible only in the schema sense. `nh prune` deletes the `raw_records`
    payloads these were rescued from, and an RSS feed serves 15 entries, so for any
    video that has since fallen out of its channel's feed window the text cannot be
    re-fetched at any price. Development path only.
    """
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
