"""cluster relevance, cluster retirement, relevance labels

Slice 4. `cluster_members` gains the relevance decision and its evidence;
`clusters` gains retirement so a deactivated seed stops generating feature rows
without its history being deleted; `relevance_labels` holds the hand labels the
thresholds are calibrated against. All additive — no existing value changes.

Revision ID: aa2d2317759c
Revises: 97de0ad3e0a9
Create Date: 2026-08-27 17:06:10.353794

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nh.db.types import JSONVariant

revision: str = "aa2d2317759c"
down_revision: str | None = "97de0ad3e0a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relevance_labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=16), nullable=False),
        sa.Column("cluster_id", sa.String(length=48), nullable=False),
        sa.Column("label", sa.Boolean(), nullable=False),
        sa.Column("labeller", sa.String(length=64), nullable=False),
        sa.Column("labelled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relevance_labels")),
        sa.UniqueConstraint("video_id", name=op.f("uq_relevance_labels_video_id")),
    )
    with op.batch_alter_table("relevance_labels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relevance_labels_cluster_id"), ["cluster_id"], unique=False
        )

    with op.batch_alter_table("cluster_members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("relevance", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("detail", JSONVariant, nullable=True))
        batch_op.create_index(
            "ix_cluster_members_cluster_type", ["cluster_id", "item_type"], unique=False
        )

    with op.batch_alter_table("clusters", schema=None) as batch_op:
        # server_default, not just the Python-side default: existing rows have no
        # value and the column is NOT NULL. Every cluster that exists today is live.
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column("retired_on", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clusters", schema=None) as batch_op:
        batch_op.drop_column("retired_on")
        batch_op.drop_column("active")

    with op.batch_alter_table("cluster_members", schema=None) as batch_op:
        batch_op.drop_index("ix_cluster_members_cluster_type")
        batch_op.drop_column("detail")
        batch_op.drop_column("relevance")

    with op.batch_alter_table("relevance_labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relevance_labels_cluster_id"))

    op.drop_table("relevance_labels")
    # ### end Alembic commands ###
