"""demand side tables

Adds the demand-side storage for Slice 3: `seed_terms` (curated per-seed article
and query mappings), `demand_snapshots` (absolute readings keyed on the day they
DESCRIBE), `demand_series` (whole-curve Trends observations, which cannot be
appended point-wise because each fetch renormalises to its own peak), plus
`scorecards.demand` and `scorecards.gap_confidence` so a gap is reconstructible
from the row that reports it. See ADR-0015.

Downgrading after collection has begun DISCARDS demand history, including the
Wikipedia backfill. Snapshots are the asset — test the downgrade on a scratch
database, never on the live one.

Revision ID: d55acea8b47f
Revises: 20a954826624
Create Date: 2026-08-27 16:02:53.493946

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nh.db.types import JSONVariant

revision: str = "d55acea8b47f"
down_revision: str | None = "20a954826624"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demand_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=256), nullable=False),
        sa.Column("geo", sa.String(length=8), nullable=False),
        sa.Column("timeframe", sa.String(length=24), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("points", JSONVariant, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_series")),
        sa.UniqueConstraint(
            "term", "geo", "timeframe", "observed_date", "source", name="uq_demand_series_day"
        ),
    )
    with op.batch_alter_table("demand_series", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_demand_series_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_demand_series_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_demand_series_term"), ["term"], unique=False)

    op.create_table(
        "demand_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=256), nullable=False),
        sa.Column("geo", sa.String(length=8), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_snapshots")),
        sa.UniqueConstraint(
            "term", "geo", "observed_date", "source", name="uq_demand_snapshots_day"
        ),
    )
    with op.batch_alter_table("demand_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_demand_snapshots_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_demand_snapshots_series", ["term", "observed_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_demand_snapshots_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_demand_snapshots_term"), ["term"], unique=False)

    op.create_table(
        "seed_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seed_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("term", sa.String(length=256), nullable=False),
        sa.Column("qid", sa.String(length=16), nullable=True),
        sa.Column("geo", sa.String(length=8), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["seed_id"], ["niche_seeds.id"], name=op.f("fk_seed_terms_seed_id_niche_seeds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seed_terms")),
        sa.UniqueConstraint("seed_id", "source", "term", name="uq_seed_terms_term"),
    )
    with op.batch_alter_table("seed_terms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seed_terms_seed_id"), ["seed_id"], unique=False)

    with op.batch_alter_table("scorecards", schema=None) as batch_op:
        batch_op.add_column(sa.Column("demand", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("gap_confidence", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scorecards", schema=None) as batch_op:
        batch_op.drop_column("gap_confidence")
        batch_op.drop_column("demand")

    with op.batch_alter_table("seed_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seed_terms_seed_id"))

    op.drop_table("seed_terms")
    with op.batch_alter_table("demand_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demand_snapshots_term"))
        batch_op.drop_index(batch_op.f("ix_demand_snapshots_source"))
        batch_op.drop_index("ix_demand_snapshots_series")
        batch_op.drop_index(batch_op.f("ix_demand_snapshots_run_id"))

    op.drop_table("demand_snapshots")
    with op.batch_alter_table("demand_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demand_series_term"))
        batch_op.drop_index(batch_op.f("ix_demand_series_source"))
        batch_op.drop_index(batch_op.f("ix_demand_series_run_id"))

    op.drop_table("demand_series")
    # ### end Alembic commands ###
