"""keyword_metrics

Revision ID: e600989a31f8
Revises: 9776d98d63ef
Create Date: 2026-08-28 13:41:34.522187

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e600989a31f8"
down_revision: str | None = "9776d98d63ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keyword_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=256), nullable=False),
        sa.Column("geo", sa.String(length=8), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("avg_monthly_searches", sa.Float(), nullable=True),
        sa.Column("three_month_change", sa.Float(), nullable=True),
        sa.Column("yoy_change", sa.Float(), nullable=True),
        sa.Column("competition", sa.String(length=32), nullable=True),
        sa.Column("competition_index", sa.Integer(), nullable=True),
        sa.Column("bid_low", sa.Float(), nullable=True),
        sa.Column("bid_high", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keyword_metrics")),
        sa.UniqueConstraint(
            "keyword", "geo", "lang", "observed_date", "source", name="uq_keyword_metrics_period"
        ),
    )
    with op.batch_alter_table("keyword_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_keyword_metrics_keyword"), ["keyword"], unique=False)
        batch_op.create_index(batch_op.f("ix_keyword_metrics_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_keyword_metrics_series", ["keyword", "observed_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_keyword_metrics_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("keyword_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_keyword_metrics_source"))
        batch_op.drop_index("ix_keyword_metrics_series")
        batch_op.drop_index(batch_op.f("ix_keyword_metrics_run_id"))
        batch_op.drop_index(batch_op.f("ix_keyword_metrics_keyword"))

    op.drop_table("keyword_metrics")
    # ### end Alembic commands ###
