"""baseline

Revision ID: ec425df1c592
Revises:
Create Date: 2026-08-27 01:14:42.654951

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nh.db.types import JSONVariant

revision: str = "ec425df1c592"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.String(length=48), nullable=False),
        sa.Column("rule", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("fired_on", sa.Date(), nullable=False),
        sa.Column("evidence", JSONVariant, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("cluster_id", "rule", "fired_on", name="uq_alerts_day"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_cluster_id"), ["cluster_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_rule"), ["rule"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_source"), ["source"], unique=False)

    op.create_table(
        "channel_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("subs", sa.BigInteger(), nullable=True),
        sa.Column("total_views", sa.BigInteger(), nullable=True),
        sa.Column("video_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_snapshots")),
        sa.UniqueConstraint(
            "channel_id", "observed_date", "source", name="uq_channel_snapshots_day"
        ),
    )
    with op.batch_alter_table("channel_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channel_snapshots_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channel_snapshots_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_snapshots_source"), ["source"], unique=False)

    op.create_table(
        "channels",
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploads_playlist", sa.String(length=32), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("topics", JSONVariant, nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("channel_id", name=op.f("pk_channels")),
    )
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_channels_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_source"), ["source"], unique=False)

    op.create_table(
        "cluster_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.String(length=48), nullable=False),
        sa.Column("item_type", sa.String(length=24), nullable=False),
        sa.Column("item_id", sa.String(length=256), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_noise", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_members")),
        sa.UniqueConstraint("item_type", "item_id", name="uq_cluster_members_item"),
    )
    with op.batch_alter_table("cluster_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cluster_members_cluster_id"), ["cluster_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cluster_members_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cluster_members_source"), ["source"], unique=False)

    op.create_table(
        "features_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.String(length=48), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("group", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("inputs_n", sa.Integer(), nullable=True),
        sa.Column("detail", JSONVariant, nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_features_daily")),
        sa.UniqueConstraint("cluster_id", "day", "name", name="uq_features_daily_metric"),
    )
    with op.batch_alter_table("features_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_features_daily_cluster_id"), ["cluster_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_features_daily_day"), ["day"], unique=False)
        batch_op.create_index(batch_op.f("ix_features_daily_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_features_daily_source"), ["source"], unique=False)

    op.create_table(
        "feed_state",
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("etag", sa.String(length=256), nullable=True),
        sa.Column("last_modified", sa.String(length=64), nullable=True),
        sa.Column("last_polled", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("hot", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("channel_id", name=op.f("pk_feed_state")),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quota_used", sa.Integer(), nullable=True),
        sa.Column("quota_budget", sa.Integer(), nullable=True),
        sa.Column("raw_written", sa.Integer(), nullable=True),
        sa.Column("rows_upserted", sa.Integer(), nullable=True),
        sa.Column("snapshots_written", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_runs_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_runs_source"), ["source"], unique=False)
        batch_op.create_index("ix_job_runs_source_started", ["source", "started_at"], unique=False)

    op.create_table(
        "niche_seeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("keywords", JSONVariant, nullable=False),
        sa.Column("geo", sa.String(length=8), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_niche_seeds")),
        sa.UniqueConstraint("slug", name=op.f("uq_niche_seeds_slug")),
    )
    op.create_table(
        "raw_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("payload", JSONVariant, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_records")),
    )
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_raw_records_lookup", ["source", "kind", "key", "at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_raw_records_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_records_source"), ["source"], unique=False)

    op.create_table(
        "scorecards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.String(length=48), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("gap", sa.Float(), nullable=True),
        sa.Column("openness", sa.Float(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("sustainability", sa.Float(), nullable=True),
        sa.Column("opportunity", sa.Float(), nullable=True),
        sa.Column("ci_low", sa.Float(), nullable=True),
        sa.Column("ci_high", sa.Float(), nullable=True),
        sa.Column("stage", sa.String(length=24), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scorecards")),
        sa.UniqueConstraint("cluster_id", "day", name="uq_scorecards_day"),
    )
    with op.batch_alter_table("scorecards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scorecards_cluster_id"), ["cluster_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scorecards_day"), ["day"], unique=False)
        batch_op.create_index(batch_op.f("ix_scorecards_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scorecards_source"), ["source"], unique=False)

    op.create_table(
        "video_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=16), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=True),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("views", sa.BigInteger(), nullable=True),
        sa.Column("likes", sa.BigInteger(), nullable=True),
        sa.Column("comments", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_snapshots")),
        sa.UniqueConstraint("video_id", "observed_date", "source", name="uq_video_snapshots_day"),
    )
    with op.batch_alter_table("video_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_video_snapshots_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_video_snapshots_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_video_snapshots_series", ["video_id", "observed_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_video_snapshots_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_snapshots_video_id"), ["video_id"], unique=False)

    op.create_table(
        "videos",
        sa.Column("video_id", sa.String(length=16), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.String(length=8), nullable=True),
        sa.Column("audio_lang", sa.String(length=16), nullable=True),
        sa.Column("tags", JSONVariant, nullable=True),
        sa.Column("topics", JSONVariant, nullable=True),
        sa.Column("is_short", sa.Boolean(), nullable=True),
        sa.Column("midroll_eligible", sa.Boolean(), nullable=True),
        sa.Column("sponsor_signal", sa.Boolean(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enriched", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("video_id", name=op.f("pk_videos")),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_videos_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_published_at"), ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_source"), ["source"], unique=False)

    op.create_table(
        "clusters",
        sa.Column("cluster_id", sa.String(length=48), nullable=False),
        sa.Column("seed_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("centroid", JSONVariant, nullable=True),
        sa.Column("member_counts", JSONVariant, nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["seed_id"], ["niche_seeds.id"], name=op.f("fk_clusters_seed_id_niche_seeds")
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_clusters")),
    )
    with op.batch_alter_table("clusters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clusters_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_clusters_seed_id"), ["seed_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_clusters_source"), ["source"], unique=False)

    op.create_table(
        "discoveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=16), nullable=False),
        sa.Column("seed_id", sa.Integer(), nullable=True),
        sa.Column("query", sa.String(length=256), nullable=False),
        sa.Column("order_by", sa.String(length=16), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["seed_id"], ["niche_seeds.id"], name=op.f("fk_discoveries_seed_id_niche_seeds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discoveries")),
        sa.UniqueConstraint(
            "video_id", "query", "order_by", "observed_date", name="uq_discoveries_day"
        ),
    )
    with op.batch_alter_table("discoveries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discoveries_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_discoveries_seed_id"), ["seed_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_discoveries_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_discoveries_video_id"), ["video_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("discoveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discoveries_video_id"))
        batch_op.drop_index(batch_op.f("ix_discoveries_source"))
        batch_op.drop_index(batch_op.f("ix_discoveries_seed_id"))
        batch_op.drop_index(batch_op.f("ix_discoveries_run_id"))

    op.drop_table("discoveries")
    with op.batch_alter_table("clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clusters_source"))
        batch_op.drop_index(batch_op.f("ix_clusters_seed_id"))
        batch_op.drop_index(batch_op.f("ix_clusters_run_id"))

    op.drop_table("clusters")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_source"))
        batch_op.drop_index(batch_op.f("ix_videos_run_id"))
        batch_op.drop_index(batch_op.f("ix_videos_published_at"))
        batch_op.drop_index(batch_op.f("ix_videos_channel_id"))

    op.drop_table("videos")
    with op.batch_alter_table("video_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_snapshots_video_id"))
        batch_op.drop_index(batch_op.f("ix_video_snapshots_source"))
        batch_op.drop_index("ix_video_snapshots_series")
        batch_op.drop_index(batch_op.f("ix_video_snapshots_run_id"))
        batch_op.drop_index(batch_op.f("ix_video_snapshots_channel_id"))

    op.drop_table("video_snapshots")
    with op.batch_alter_table("scorecards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scorecards_source"))
        batch_op.drop_index(batch_op.f("ix_scorecards_run_id"))
        batch_op.drop_index(batch_op.f("ix_scorecards_day"))
        batch_op.drop_index(batch_op.f("ix_scorecards_cluster_id"))

    op.drop_table("scorecards")
    with op.batch_alter_table("raw_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_records_source"))
        batch_op.drop_index(batch_op.f("ix_raw_records_run_id"))
        batch_op.drop_index("ix_raw_records_lookup")

    op.drop_table("raw_records")
    op.drop_table("niche_seeds")
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_job_runs_source_started")
        batch_op.drop_index(batch_op.f("ix_job_runs_source"))
        batch_op.drop_index(batch_op.f("ix_job_runs_run_id"))

    op.drop_table("job_runs")
    op.drop_table("feed_state")
    with op.batch_alter_table("features_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_features_daily_source"))
        batch_op.drop_index(batch_op.f("ix_features_daily_run_id"))
        batch_op.drop_index(batch_op.f("ix_features_daily_day"))
        batch_op.drop_index(batch_op.f("ix_features_daily_cluster_id"))

    op.drop_table("features_daily")
    with op.batch_alter_table("cluster_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cluster_members_source"))
        batch_op.drop_index(batch_op.f("ix_cluster_members_run_id"))
        batch_op.drop_index(batch_op.f("ix_cluster_members_cluster_id"))

    op.drop_table("cluster_members")
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channels_source"))
        batch_op.drop_index(batch_op.f("ix_channels_run_id"))

    op.drop_table("channels")
    with op.batch_alter_table("channel_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_snapshots_source"))
        batch_op.drop_index(batch_op.f("ix_channel_snapshots_run_id"))
        batch_op.drop_index(batch_op.f("ix_channel_snapshots_channel_id"))

    op.drop_table("channel_snapshots")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_source"))
        batch_op.drop_index(batch_op.f("ix_alerts_run_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_rule"))
        batch_op.drop_index(batch_op.f("ix_alerts_cluster_id"))

    op.drop_table("alerts")
    # ### end Alembic commands ###
