"""The backtest niche set. Curated before the data it will be measured against.

Gate E needs ~30 niches, not 6: Spearman's SE is about `1/sqrt(N-1)`, so at N=6 the
smallest correlation distinguishable from noise is **0.89** and a null result would
mean nothing. At N=30 it is 0.37. Building these is the real cost of Slice 6.

**Six families of six, not one flat set of thirty.** `lexicon.weights()` scores a
term `1/k` over the family and zeroes any term present in all of it, so family size
is part of the instrument rather than an implementation detail. In a family of two a
shared term IS in every lexicon and weighs 0; in the live family of five, `collapse`
sits in two and weighs 0.5. A flat family of thirty would push most shared terms to
1/6 or lower and the zero row would essentially never fire — the backtest's
relevance rule would be systematically stricter than production's at the same 0.55
threshold, which is a confound directly under the headline. Families of six
reproduce the live construction of five closely.

**These are backtest niches, not production seeds.** They live here, not in
`nh/seeds.py`; the live portfolio stays at 6 and tonight's cron is unaffected. They
are scored with `weights(BACKTEST_LEXICONS[family], BACKTEST_COMMON)`, never
against the live family — see ADR-0026 and `tests/test_lexicon_families.py` for the
measured reason that matters.

**Curated blind, and checkably so.** This file is committed before
`yt_metadata_en.jsonl.gz` finishes downloading. Writing a lexicon, discovering it
selects four channels, and widening it is tuning the definition of the population
against the population — so the sequencing makes that impossible rather than merely
discouraged, and the report cites this commit against the file's mtime.

The inclusion floor is fixed here, before the scan, and niches that fall below it
are **reported as dropped with their counts, never rescued by an edit**. 36 are
curated expecting ~30 to survive.
"""

from __future__ import annotations

#: Genre vocabulary shared by every backtest family, weighing 0 by construction —
#: the same job `lexicon._COMMON` does for the live set. These are how a
#: documentary-analysis niche is *phrased*, not what separates one from another.
BACKTEST_COMMON: tuple[str, ...] = (
    "disaster",
    "documentary",
    "investigation",
    "analysis",
    "explained",
    "story",
    "history",
    "failure",
    "tragedy",
    "inside",
    "truth",
    "happened",
    "case",
    "real",
)

#: A channel joins a niche only with at least this many on-niche videos, and a niche
#: enters the backtest only with at least this many member channels. FIXED BEFORE THE
#: SCAN. A niche below the floor is dropped and reported, not rescued.
MIN_ON_NICHE_VIDEOS = 5
MIN_MEMBER_CHANNELS = 15


#: One entry per niche. Shape mirrors `nh/seeds.py::SEEDS` deliberately — a new
#: shape here would be a second thing to learn for no gain.
#:
#: `wiki_event_pool` names the POOL, not the articles. `scripts/select_demand_articles.py`
#: draws a fixed-K uniform sample from it with the seed recorded. Hand-picking event
#: articles is what ADR-0022 forbids, with a measured cost: it inflated aviation's
#: event stratum thirteen-fold. Across 36 niches it would poison every demand series.
BACKTEST_NICHES: tuple[dict, ...] = (
    # --- family: catastrophic-failure -- sudden physical failures of built things
    {
        "slug": "nuclear-accidents",
        "label": "Nuclear accidents",
        "family": "catastrophic-failure",
        "geo": "US",
        "lexicon": (
            "nuclear",
            "reactor",
            "radiation",
            "radioactive",
            "meltdown",
            "fallout",
            "coolant",
            "containment",
            "fuel rod",
            "core",
            "isotope",
            "becquerel",
            "sievert",
            "chernobyl",
            "fukushima",
            "three mile island",
            "iaea",
            "criticality",
            "scram",
            "cooling system",
            "steam explosion",
            "graphite",
            "exclusion zone",
            "evacuation",
            "decommissioning",
            "spent fuel",
            "plutonium",
            "uranium",
            "enrichment",
            "power plant",
            "turbine hall",
            "control rod",
            "pressure vessel",
            "primary loop",
            "operator error",
            "safety test",
            "regulator",
            "nrc",
            "half life",
            "contamination",
        ),
        "wiki_topic": (
            "Nuclear_power_plant_accidents_and_incidents",
            "Nuclear_safety_and_security",
            "Radioactive_contamination",
        ),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Nuclear accidents and incidents"],
        },
    },
    {
        "slug": "mining-disasters",
        "label": "Mining disasters",
        "family": "catastrophic-failure",
        "geo": "US",
        "lexicon": (
            "mine",
            "miner",
            "mining",
            "colliery",
            "pit",
            "shaft",
            "seam",
            "coal",
            "tunnel",
            "underground",
            "cave in",
            "roof fall",
            "firedamp",
            "methane",
            "gas explosion",
            "dust explosion",
            "rescue team",
            "trapped",
            "winch",
            "cage",
            "ventilation",
            "subsidence",
            "tailings",
            "slurry",
            "spoil tip",
            "quarry",
            "ore",
            "extraction",
            "drilling",
            "blasting",
            "helmet",
            "canary",
            "damp",
            "inrush",
            "flooding",
            "haulage",
            "safety lamp",
            "inspectorate",
            "msha",
            "pit head",
        ),
        "wiki_topic": ("Mining_accident", "Coal_mining", "Mine_safety"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Mining disasters"]},
    },
    {
        "slug": "industrial-explosions",
        "label": "Industrial explosions",
        "family": "catastrophic-failure",
        "geo": "US",
        "lexicon": (
            "explosion",
            "blast",
            "detonation",
            "refinery",
            "plant",
            "factory",
            "chemical",
            "petrochemical",
            "storage tank",
            "vapour cloud",
            "vapor cloud",
            "flammable",
            "ignition",
            "overpressure",
            "shockwave",
            "ammonium nitrate",
            "fertiliser",
            "fertilizer",
            "silo",
            "boiler",
            "pressure vessel",
            "rupture",
            "valve",
            "relief",
            "flare",
            "leak",
            "spill",
            "toxic",
            "hazmat",
            "osha",
            "csb",
            "process safety",
            "runaway reaction",
            "shutdown",
            "maintenance",
            "shift",
            "operator",
            "warehouse",
            "port",
            "industrial park",
        ),
        "wiki_topic": ("Industrial_disaster", "Explosion", "Process_safety"),
        "wiki_event_pool": {
            "classes": ["Q68800046"],
            "categories": ["Category:Industrial fires and explosions"],
        },
    },
    {
        "slug": "dam-failures",
        "label": "Dam failures",
        "family": "catastrophic-failure",
        "geo": "US",
        "lexicon": (
            "dam",
            "reservoir",
            "spillway",
            "embankment",
            "levee",
            "dike",
            "breach",
            "overtopping",
            "seepage",
            "piping",
            "abutment",
            "impoundment",
            "hydro",
            "hydroelectric",
            "floodwater",
            "inundation",
            "downstream",
            "valley",
            "earthfill",
            "concrete arch",
            "gravity dam",
            "tailings dam",
            "sluice",
            "gate",
            "penstock",
            "catchment",
            "watershed",
            "silt",
            "erosion",
            "foundation",
            "geology",
            "saturation",
            "crest",
            "freeboard",
            "monitoring",
            "instrumentation",
            "evacuation",
            "washed away",
            "torrent",
            "flood wave",
        ),
        "wiki_topic": ("Dam_failure", "Dam", "Flood_control"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Dam failures"]},
    },
    {
        "slug": "bridge-collapses",
        "label": "Bridge collapses",
        "family": "catastrophic-failure",
        "geo": "US",
        "lexicon": (
            "bridge",
            "span",
            "girder",
            "truss",
            "cantilever",
            "suspension",
            "cable",
            "pier",
            "pylon",
            "deck",
            "bearing",
            "expansion joint",
            "gusset plate",
            "rivet",
            "weld",
            "fatigue",
            "corrosion",
            "scour",
            "load rating",
            "overload",
            "resonance",
            "aeroelastic",
            "flutter",
            "viaduct",
            "overpass",
            "footbridge",
            "approach",
            "abutment",
            "buckling",
            "shear",
            "tension",
            "compression",
            "inspection",
            "structurally deficient",
            "retrofit",
            "collapsed",
            "plunged",
            "traffic",
            "engineer",
            "design flaw",
        ),
        "wiki_topic": ("List_of_bridge_failures", "Bridge", "Structural_integrity_and_failure"),
        "wiki_event_pool": {"classes": ["Q1309431"], "categories": ["Category:Bridge disasters"]},
    },
    {
        "slug": "building-fires",
        "label": "Building fires",
        "family": "catastrophic-failure",
        "geo": "US",
        "lexicon": (
            "fire",
            "blaze",
            "smoke",
            "flame",
            "burned",
            "sprinkler",
            "alarm",
            "extinguisher",
            "hydrant",
            "firefighter",
            "brigade",
            "ladder",
            "escape",
            "stairwell",
            "exit",
            "cladding",
            "insulation",
            "combustible",
            "flammable",
            "arson",
            "electrical fault",
            "wiring",
            "short circuit",
            "high rise",
            "tower block",
            "nightclub",
            "theatre",
            "hotel",
            "warehouse",
            "occupancy",
            "capacity",
            "code violation",
            "inspection",
            "smoke inhalation",
            "toxic",
            "evacuate",
            "trapped",
            "rescue",
            "compartmentation",
            "fire door",
        ),
        "wiki_topic": ("Structure_fire", "Fire_safety", "Building_code"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Building and structure fires"]},
    },
    # --- family: transport-loss -- vehicles and vessels lost in service
    {
        "slug": "rail-disasters",
        "label": "Rail disasters",
        "family": "transport-loss",
        "geo": "US",
        "lexicon": (
            "train",
            "rail",
            "railway",
            "railroad",
            "locomotive",
            "carriage",
            "coach",
            "wagon",
            "derail",
            "derailment",
            "track",
            "sleeper",
            "ballast",
            "points",
            "switch",
            "signal",
            "signalling",
            "junction",
            "level crossing",
            "gradient",
            "brake",
            "airbrake",
            "coupling",
            "bogie",
            "axle",
            "wheel",
            "rail joint",
            "buckled rail",
            "speed restriction",
            "overspeed",
            "driver",
            "guard",
            "dispatcher",
            "collision",
            "head on",
            "shunting",
            "freight",
            "commuter",
            "ntsb rail",
            "rail inspector",
        ),
        "wiki_topic": ("List_of_rail_accidents", "Railway_accident", "Railway_signalling"),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Railway accidents and incidents"],
        },
    },
    {
        "slug": "space-accidents",
        "label": "Space accidents",
        "family": "transport-loss",
        "geo": "US",
        "lexicon": (
            "rocket",
            "launch",
            "spacecraft",
            "capsule",
            "orbit",
            "orbital",
            "booster",
            "stage",
            "payload",
            "fairing",
            "propellant",
            "cryogenic",
            "o ring",
            "solid booster",
            "reentry",
            "heat shield",
            "tile",
            "abort",
            "escape tower",
            "astronaut",
            "cosmonaut",
            "crew",
            "mission control",
            "telemetry",
            "nasa",
            "roscosmos",
            "shuttle",
            "soyuz",
            "apollo",
            "challenger",
            "columbia",
            "pad",
            "countdown",
            "anomaly",
            "loss of vehicle",
            "depressurisation",
            "depressurization",
            "docking",
            "spacewalk",
            "flight readiness",
        ),
        "wiki_topic": (
            "List_of_spaceflight-related_accidents_and_incidents",
            "Spaceflight",
            "Human_spaceflight",
        ),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Spaceflight-related accidents and incidents"],
        },
    },
    {
        "slug": "submarine-losses",
        "label": "Submarine losses",
        "family": "transport-loss",
        "geo": "US",
        "lexicon": (
            "submarine",
            "sub",
            "submersible",
            "boat",
            "hull",
            "pressure hull",
            "ballast",
            "trim",
            "periscope",
            "conning tower",
            "torpedo",
            "torpedo room",
            "reactor compartment",
            "crush depth",
            "test depth",
            "implosion",
            "flooding",
            "escape trunk",
            "rescue bell",
            "dsrv",
            "sonar",
            "hydrophone",
            "acoustic",
            "seabed",
            "wreck site",
            "salvage",
            "crew lost",
            "hatch",
            "snorkel",
            "diesel electric",
            "nuclear submarine",
            "patrol",
            "dive",
            "surface",
            "buoyancy",
            "compartment",
            "watertight",
            "navy",
            "kursk",
            "thresher",
        ),
        "wiki_topic": ("List_of_sunken_nuclear_submarines", "Submarine", "Submarine_rescue"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Submarine accidents"]},
    },
    {
        "slug": "helicopter-crashes",
        "label": "Helicopter crashes",
        "family": "transport-loss",
        "geo": "US",
        "lexicon": (
            "helicopter",
            "rotor",
            "main rotor",
            "tail rotor",
            "rotorcraft",
            "blade",
            "swashplate",
            "gearbox",
            "transmission",
            "autorotation",
            "hover",
            "vortex ring",
            "retreating blade",
            "mast bumping",
            "settling with power",
            "pilot",
            "cockpit",
            "hoist",
            "winch",
            "medevac",
            "air ambulance",
            "offshore",
            "rig",
            "sling load",
            "downwash",
            "landing skid",
            "helipad",
            "wire strike",
            "brownout",
            "whiteout",
            "night vision",
            "collective",
            "cyclic",
            "torque",
            "turbine",
            "engine failure",
            "crashed",
            "faa",
            "airworthiness",
            "maintenance",
        ),
        "wiki_topic": ("Helicopter", "Aviation_safety", "Autorotation"),
        "wiki_event_pool": {
            "classes": ["Q744913"],
            "categories": ["Category:Helicopter accidents and incidents"],
        },
    },
    {
        "slug": "road-coach-crashes",
        "label": "Road and coach crashes",
        "family": "transport-loss",
        "geo": "US",
        "lexicon": (
            "bus",
            "coach",
            "lorry",
            "truck",
            "tanker",
            "motorway",
            "highway",
            "interstate",
            "carriageway",
            "junction",
            "roundabout",
            "guardrail",
            "barrier",
            "crash barrier",
            "pileup",
            "jackknife",
            "rollover",
            "skid",
            "aquaplane",
            "brake failure",
            "tyre blowout",
            "tire blowout",
            "driver",
            "fatigue",
            "tachograph",
            "hours of service",
            "seatbelt",
            "passenger",
            "coach party",
            "school bus",
            "crossing",
            "speed limit",
            "black spot",
            "collision",
            "head on",
            "roadworks",
            "visibility",
            "fog",
            "black ice",
            "highway patrol",
        ),
        "wiki_topic": ("Traffic_collision", "Road_traffic_safety", "Bus"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Bus incidents"]},
    },
    {
        "slug": "pipeline-failures",
        "label": "Pipeline failures",
        "family": "transport-loss",
        "geo": "US",
        "lexicon": (
            "pipeline",
            "pipe",
            "conduit",
            "gas main",
            "oil pipeline",
            "transmission line",
            "rupture",
            "leak",
            "seep",
            "corrosion",
            "stress corrosion",
            "weld defect",
            "girth weld",
            "cathodic protection",
            "coating",
            "pig",
            "smart pig",
            "inline inspection",
            "hydrostatic test",
            "pressure test",
            "maop",
            "compressor station",
            "pump station",
            "valve",
            "shutoff",
            "isolation",
            "right of way",
            "excavator",
            "third party damage",
            "one call",
            "odorant",
            "methane",
            "crude",
            "condensate",
            "spill",
            "release",
            "phmsa",
            "operator",
            "integrity management",
            "geohazard",
            "landslide",
        ),
        "wiki_topic": ("Pipeline_transport", "Pipeline_accident", "Corrosion"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Pipeline accidents"]},
    },
    # --- family: financial-collapse -- money lost through fraud or failure
    {
        "slug": "ponzi-schemes",
        "label": "Ponzi schemes",
        "family": "financial-collapse",
        "geo": "US",
        "lexicon": (
            "ponzi",
            "pyramid scheme",
            "madoff",
            "investor",
            "returns",
            "payout",
            "redemption",
            "feeder fund",
            "hedge fund",
            "wealth management",
            "guaranteed return",
            "too good to be true",
            "recruit",
            "downline",
            "affinity fraud",
            "clawback",
            "trustee",
            "receiver",
            "restitution",
            "victims",
            "life savings",
            "sec charges",
            "wire fraud",
            "mail fraud",
            "indictment",
            "sentenced",
            "prison",
            "collapse",
            "unravel",
            "withdrawal",
            "liquidity",
            "fabricated statement",
            "phantom",
            "audit",
            "whistleblower",
            "regulator",
            "registered adviser",
            "custody",
            "due diligence",
            "returns fraud",
        ),
        "wiki_topic": ("Ponzi_scheme", "Securities_fraud", "Investment_fraud"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Ponzi schemes"]},
    },
    {
        "slug": "bank-failures",
        "label": "Bank failures",
        "family": "financial-collapse",
        "geo": "US",
        "lexicon": (
            "bank",
            "banking",
            "deposit",
            "depositor",
            "bank run",
            "liquidity",
            "solvency",
            "capital ratio",
            "tier 1",
            "leverage",
            "balance sheet",
            "mortgage",
            "subprime",
            "securitisation",
            "securitization",
            "cdo",
            "credit default swap",
            "counterparty",
            "interbank",
            "central bank",
            "lender of last resort",
            "bailout",
            "nationalisation",
            "nationalization",
            "fdic",
            "receivership",
            "resolution",
            "insolvent",
            "write down",
            "toxic asset",
            "stress test",
            "regulator",
            "basel",
            "contagion",
            "credit crunch",
            "collapse",
            "lehman",
            "northern rock",
            "savings",
            "branch",
        ),
        "wiki_topic": ("Bank_failure", "Bank_run", "Financial_crisis"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Bank failures"]},
    },
    {
        "slug": "crypto-collapses",
        "label": "Crypto collapses",
        "family": "financial-collapse",
        "geo": "US",
        "lexicon": (
            "crypto",
            "cryptocurrency",
            "bitcoin",
            "ethereum",
            "token",
            "coin",
            "exchange",
            "wallet",
            "private key",
            "cold storage",
            "hot wallet",
            "stablecoin",
            "depeg",
            "defi",
            "smart contract",
            "rug pull",
            "mint",
            "liquidity pool",
            "yield farming",
            "staking",
            "blockchain",
            "ledger",
            "mining",
            "hash rate",
            "halving",
            "ico",
            "whitepaper",
            "airdrop",
            "commingled funds",
            "custody",
            "insolvency",
            "withdrawal halt",
            "bankruptcy filing",
            "ftx",
            "mt gox",
            "terra",
            "luna",
            "celsius",
            "exchange hack",
            "on chain",
        ),
        "wiki_topic": ("Cryptocurrency", "Cryptocurrency_bubble", "Cryptocurrency_exchange"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Cryptocurrency companies"]},
    },
    {
        "slug": "accounting-frauds",
        "label": "Accounting frauds",
        "family": "financial-collapse",
        "geo": "US",
        "lexicon": (
            "accounting",
            "auditor",
            "audit",
            "restatement",
            "earnings",
            "revenue recognition",
            "off balance sheet",
            "special purpose entity",
            "mark to market",
            "cookie jar",
            "channel stuffing",
            "round tripping",
            "capitalised expense",
            "capitalized expense",
            "goodwill",
            "impairment",
            "write off",
            "gaap",
            "ifrs",
            "sarbanes oxley",
            "internal control",
            "material weakness",
            "cfo",
            "controller",
            "ledger",
            "journal entry",
            "reconciliation",
            "shell company",
            "related party",
            "disclosure",
            "10 k",
            "sec filing",
            "enron",
            "worldcom",
            "wirecard",
            "satyam",
            "forensic accountant",
            "short seller",
            "whistleblower",
            "delisted",
        ),
        "wiki_topic": ("Accounting_scandals", "Creative_accounting", "Auditor_independence"),
        "wiki_event_pool": {
            "classes": ["Q4215744"],
            "categories": ["Category:Accounting scandals"],
        },
    },
    {
        "slug": "insider-trading",
        "label": "Insider trading cases",
        "family": "financial-collapse",
        "geo": "US",
        "lexicon": (
            "insider",
            "insider trading",
            "material nonpublic",
            "tipper",
            "tippee",
            "front running",
            "wiretap",
            "expert network",
            "hedge fund manager",
            "portfolio manager",
            "analyst",
            "earnings call",
            "blackout period",
            "10b5",
            "rule 10b5 1",
            "sec enforcement",
            "civil penalty",
            "disgorgement",
            "cooperating witness",
            "plea",
            "conviction",
            "appeal",
            "second circuit",
            "prosecutor",
            "sac capital",
            "galleon",
            "raj",
            "trading records",
            "brokerage",
            "options",
            "call options",
            "unusual volume",
            "merger arbitrage",
            "takeover",
            "leak",
            "confidential",
            "fiduciary",
            "duty",
            "misappropriation",
            "compliance",
        ),
        "wiki_topic": (
            "Insider_trading",
            "Securities_regulation_in_the_United_States",
            "U.S._Securities_and_Exchange_Commission",
        ),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Insider trading"]},
    },
    {
        "slug": "product-recalls",
        "label": "Product recalls",
        "family": "financial-collapse",
        "geo": "US",
        "lexicon": (
            "recall",
            "defect",
            "safety notice",
            "consumer",
            "manufacturer",
            "supplier",
            "batch",
            "lot number",
            "serial number",
            "vin",
            "airbag",
            "ignition switch",
            "brake defect",
            "battery",
            "lithium ion",
            "overheat",
            "thermal runaway",
            "fire risk",
            "choking hazard",
            "contaminant",
            "labelling",
            "mislabelled",
            "class action",
            "liability",
            "settlement",
            "cpsc",
            "nhtsa",
            "fda recall",
            "warning letter",
            "field action",
            "service bulletin",
            "remedy",
            "repair",
            "replacement",
            "refund",
            "injury reports",
            "complaint",
            "investigation opened",
            "cover up",
            "engineering change",
        ),
        "wiki_topic": ("Product_recall", "Product_liability", "Consumer_protection"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Product recalls"]},
    },
    # --- family: crime-and-law -- offences and the proceedings that follow
    {
        "slug": "wrongful-convictions",
        "label": "Wrongful convictions",
        "family": "crime-and-law",
        "geo": "US",
        "lexicon": (
            "wrongful",
            "exoneration",
            "exonerated",
            "innocence project",
            "dna testing",
            "post conviction",
            "habeas",
            "appeal",
            "retrial",
            "vacated",
            "overturned",
            "misidentification",
            "eyewitness",
            "lineup",
            "false confession",
            "interrogation",
            "coerced",
            "jailhouse informant",
            "snitch",
            "brady violation",
            "withheld evidence",
            "prosecutorial misconduct",
            "ineffective counsel",
            "public defender",
            "forensic error",
            "bite mark",
            "hair comparison",
            "arson science",
            "compensation",
            "years served",
            "death row",
            "clemency",
            "pardon",
            "conviction integrity",
            "cold case",
            "actual innocence",
            "sentence",
            "parole",
            "release",
            "record expunged",
        ),
        "wiki_topic": ("Miscarriage_of_justice", "Innocence_Project", "Exoneration"),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Overturned convictions in the United States"],
        },
    },
    {
        "slug": "heists-and-robberies",
        "label": "Heists and robberies",
        "family": "crime-and-law",
        "geo": "US",
        "lexicon": (
            "heist",
            "robbery",
            "burglary",
            "vault",
            "safe",
            "safe deposit",
            "armoured",
            "armored",
            "security van",
            "getaway",
            "accomplice",
            "crew",
            "inside job",
            "tunnel",
            "drill",
            "thermal lance",
            "alarm bypass",
            "cctv",
            "surveillance",
            "loot",
            "bullion",
            "diamonds",
            "cash",
            "unsolved",
            "manhunt",
            "fence",
            "laundering",
            "recovered",
            "stolen",
            "bank job",
            "armed",
            "hostage",
            "police pursuit",
            "fingerprint",
            "getaway car",
            "stakeout",
            "informant",
            "sentence",
            "gang",
            "planning",
        ),
        "wiki_topic": ("Robbery", "Bank_robbery", "Burglary"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Bank robberies"]},
    },
    {
        "slug": "art-thefts",
        "label": "Art thefts and forgeries",
        "family": "crime-and-law",
        "geo": "US",
        "lexicon": (
            "art",
            "painting",
            "canvas",
            "gallery",
            "museum",
            "curator",
            "collection",
            "provenance",
            "attribution",
            "forgery",
            "forger",
            "fake",
            "copy",
            "authentication",
            "connoisseur",
            "pigment analysis",
            "carbon dating",
            "craquelure",
            "restorer",
            "auction",
            "sotheby",
            "christie",
            "dealer",
            "catalogue raisonne",
            "stolen artwork",
            "looted",
            "restitution",
            "interpol",
            "art squad",
            "recovered painting",
            "ransom",
            "cut from frame",
            "heist museum",
            "masterpiece",
            "old master",
            "expert opinion",
            "certificate",
            "signature",
            "wildenstein",
            "beltracchi",
        ),
        "wiki_topic": ("Art_theft", "Art_forgery", "Provenance"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Art forgers"]},
    },
    {
        "slug": "missing-persons",
        "label": "Missing persons cases",
        "family": "crime-and-law",
        "geo": "US",
        "lexicon": (
            "missing",
            "disappeared",
            "vanished",
            "last seen",
            "search party",
            "ground search",
            "cadaver dog",
            "sonar search",
            "dive team",
            "remains",
            "identification",
            "dental records",
            "familial dna",
            "genetic genealogy",
            "cold case",
            "reward",
            "tip line",
            "person of interest",
            "suspect",
            "timeline",
            "cell tower",
            "last ping",
            "cctv sighting",
            "abduction",
            "runaway",
            "foul play",
            "presumed dead",
            "declared dead",
            "family appeal",
            "namus",
            "doe",
            "unidentified",
            "amber alert",
            "investigation reopened",
            "witness statement",
            "polygraph",
            "alibi",
            "vehicle found",
            "campsite",
            "trailhead",
        ),
        "wiki_topic": ("Missing_person", "Cold_case", "Forensic_identification"),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Missing person cases in the United States"],
        },
    },
    {
        "slug": "organised-crime",
        "label": "Organised crime",
        "family": "crime-and-law",
        "geo": "US",
        "lexicon": (
            "mafia",
            "mob",
            "cosa nostra",
            "cartel",
            "syndicate",
            "boss",
            "underboss",
            "capo",
            "soldier",
            "family",
            "racketeering",
            "rico",
            "extortion",
            "protection racket",
            "loan sharking",
            "bookmaking",
            "numbers racket",
            "smuggling",
            "trafficking",
            "money laundering",
            "front business",
            "informant",
            "witness protection",
            "turncoat",
            "omerta",
            "hit",
            "contract killing",
            "enforcer",
            "territory",
            "turf war",
            "indictment",
            "wiretap",
            "surveillance",
            "task force",
            "fbi",
            "prosecution",
            "conviction",
            "sentenced",
            "empire",
            "kingpin",
        ),
        "wiki_topic": (
            "Organized_crime",
            "Racketeer_Influenced_and_Corrupt_Organizations_Act",
            "American_Mafia",
        ),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Organized crime"]},
    },
    {
        "slug": "espionage-cases",
        "label": "Espionage cases",
        "family": "crime-and-law",
        "geo": "US",
        "lexicon": (
            "spy",
            "espionage",
            "agent",
            "handler",
            "asset",
            "mole",
            "double agent",
            "defector",
            "tradecraft",
            "dead drop",
            "brush pass",
            "cipher",
            "cryptography",
            "signals intelligence",
            "counterintelligence",
            "cia",
            "kgb",
            "mi5",
            "mi6",
            "stasi",
            "classified",
            "top secret",
            "clearance",
            "leak",
            "exfiltration",
            "surveillance",
            "shadowing",
            "safe house",
            "cover identity",
            "legend",
            "recruitment",
            "blackmail",
            "treason",
            "official secrets",
            "polygraph",
            "damage assessment",
            "arrest",
            "exchange",
            "spy swap",
            "sentenced",
            "prosecution",
        ),
        "wiki_topic": ("Espionage", "Counterintelligence", "Cold_War_espionage"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Espionage"]},
    },
    # --- family: health-and-environment -- harm at population scale
    {
        "slug": "pandemics",
        "label": "Pandemics and outbreaks",
        "family": "health-and-environment",
        "geo": "US",
        "lexicon": (
            "pandemic",
            "epidemic",
            "outbreak",
            "virus",
            "viral",
            "bacterium",
            "pathogen",
            "strain",
            "variant",
            "zoonotic",
            "spillover",
            "reservoir",
            "transmission",
            "airborne",
            "droplet",
            "incubation",
            "asymptomatic",
            "case fatality",
            "reproduction number",
            "herd immunity",
            "quarantine",
            "isolation",
            "lockdown",
            "contact tracing",
            "vaccine",
            "vaccination",
            "immunisation",
            "immunization",
            "antiviral",
            "who",
            "cdc",
            "epidemiology",
            "surveillance",
            "index case",
            "cluster",
            "wave",
            "mortality",
            "excess deaths",
            "public health",
            "containment",
        ),
        "wiki_topic": ("Pandemic", "Epidemiology", "Public_health"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Pandemics"]},
    },
    {
        "slug": "pharmaceutical-scandals",
        "label": "Pharmaceutical scandals",
        "family": "health-and-environment",
        "geo": "US",
        "lexicon": (
            "drug",
            "pharmaceutical",
            "clinical trial",
            "phase iii",
            "placebo",
            "adverse event",
            "side effect",
            "black box warning",
            "withdrawal",
            "marketing authorisation",
            "approval",
            "fda",
            "ema",
            "off label",
            "prescription",
            "opioid",
            "thalidomide",
            "vioxx",
            "teratogenic",
            "birth defect",
            "litigation",
            "settlement",
            "class action",
            "plaintiff",
            "ghostwriting",
            "publication bias",
            "suppressed data",
            "trial registry",
            "detailing",
            "kickback",
            "false claims",
            "whistleblower",
            "consent decree",
            "manufacturing",
            "contamination",
            "generic",
            "patent",
            "pricing",
            "compounding",
            "recall notice",
        ),
        "wiki_topic": ("Pharmaceutical_industry", "Drug_safety", "Clinical_trial"),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Pharmaceutical industry scandals"],
        },
    },
    {
        "slug": "environmental-disasters",
        "label": "Environmental disasters",
        "family": "health-and-environment",
        "geo": "US",
        "lexicon": (
            "oil spill",
            "slick",
            "tanker",
            "blowout",
            "wellhead",
            "drilling rig",
            "dispersant",
            "boom",
            "shoreline",
            "wetland",
            "wildlife",
            "oiled bird",
            "habitat",
            "ecosystem",
            "remediation",
            "cleanup",
            "superfund",
            "epa",
            "discharge",
            "effluent",
            "pollutant",
            "heavy metal",
            "mercury",
            "pcb",
            "dioxin",
            "groundwater",
            "aquifer",
            "runoff",
            "deforestation",
            "smog",
            "acid rain",
            "emission",
            "toxic release",
            "fine",
            "consent order",
            "long term damage",
            "restoration",
            "fishery",
            "closure",
        ),
        "wiki_topic": ("Environmental_disaster", "Oil_spill", "Pollution"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Environmental disasters"]},
    },
    {
        "slug": "water-contamination",
        "label": "Water contamination events",
        "family": "health-and-environment",
        "geo": "US",
        "lexicon": (
            "water",
            "drinking water",
            "supply",
            "treatment plant",
            "distribution",
            "main",
            "service line",
            "lead pipe",
            "corrosion control",
            "orthophosphate",
            "chlorine",
            "chloramine",
            "disinfection",
            "byproduct",
            "coliform",
            "cryptosporidium",
            "legionella",
            "nitrate",
            "arsenic",
            "pfas",
            "forever chemical",
            "testing",
            "sampling",
            "exceedance",
            "action level",
            "boil notice",
            "advisory",
            "municipal",
            "utility",
            "state regulator",
            "safe drinking water act",
            "flint",
            "residents",
            "blood lead",
            "filter",
            "bottled water",
            "pipe replacement",
            "public notification",
            "cover up",
            "health department",
        ),
        "wiki_topic": ("Water_pollution", "Drinking_water_quality_standards", "Lead_poisoning"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Water pollution"]},
    },
    {
        "slug": "food-safety-failures",
        "label": "Food safety failures",
        "family": "health-and-environment",
        "geo": "US",
        "lexicon": (
            "food",
            "foodborne",
            "salmonella",
            "listeria",
            "e coli",
            "campylobacter",
            "botulism",
            "norovirus",
            "contaminated",
            "adulterated",
            "melamine",
            "horsemeat",
            "mislabelled",
            "supply chain",
            "processing plant",
            "slaughterhouse",
            "abattoir",
            "cold chain",
            "temperature abuse",
            "pasteurisation",
            "pasteurization",
            "sanitation",
            "haccp",
            "inspection",
            "usda",
            "fsis",
            "outbreak strain",
            "whole genome sequencing",
            "traceback",
            "recall notice",
            "illness cluster",
            "hospitalisation",
            "hospitalization",
            "produce",
            "leafy greens",
            "peanut",
            "infant formula",
            "import alert",
            "audit",
            "supplier",
        ),
        "wiki_topic": ("Foodborne_illness", "Food_safety", "Food_contaminant"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Foodborne illness outbreaks"]},
    },
    {
        "slug": "occupational-health",
        "label": "Occupational health scandals",
        "family": "health-and-environment",
        "geo": "US",
        "lexicon": (
            "asbestos",
            "mesothelioma",
            "silicosis",
            "black lung",
            "pneumoconiosis",
            "benzene",
            "solvent",
            "exposure limit",
            "permissible exposure",
            "respirator",
            "ppe",
            "ventilation",
            "dust",
            "fibre",
            "fiber",
            "workplace",
            "shop floor",
            "shipyard",
            "foundry",
            "textile mill",
            "latency",
            "diagnosis",
            "compensation claim",
            "workers compensation",
            "industrial disease",
            "epidemiological study",
            "cohort",
            "employer",
            "suppressed research",
            "internal memo",
            "liability",
            "trust fund",
            "bankruptcy shield",
            "osha citation",
            "union",
            "safety committee",
            "medical surveillance",
            "screening",
            "removal",
            "abatement",
        ),
        "wiki_topic": (
            "Occupational_safety_and_health",
            "Asbestos_and_the_law",
            "Occupational_disease",
        ),
        "wiki_event_pool": {
            "classes": [],
            "categories": ["Category:Occupational safety and health"],
        },
    },
    # --- family: systems-and-security -- failures of software and networks
    {
        "slug": "cyberattacks",
        "label": "Cyberattacks",
        "family": "systems-and-security",
        "geo": "US",
        "lexicon": (
            "cyberattack",
            "hacker",
            "intrusion",
            "breach",
            "malware",
            "ransomware",
            "trojan",
            "worm",
            "botnet",
            "command and control",
            "payload",
            "exploit",
            "zero day",
            "vulnerability",
            "patch",
            "phishing",
            "spear phishing",
            "credential",
            "lateral movement",
            "privilege escalation",
            "exfiltration",
            "encryption key",
            "ransom demand",
            "bitcoin payment",
            "incident response",
            "forensics",
            "attribution",
            "threat actor",
            "apt",
            "nation state",
            "supply chain attack",
            "backdoor",
            "firewall",
            "intrusion detection",
            "soc",
            "ciso",
            "downtime",
            "restore from backup",
            "air gap",
            "cisa",
        ),
        "wiki_topic": ("Cyberattack", "Computer_security", "Ransomware"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Cyberattacks"]},
    },
    {
        "slug": "data-breaches",
        "label": "Data breaches",
        "family": "systems-and-security",
        "geo": "US",
        "lexicon": (
            "data breach",
            "personal data",
            "pii",
            "record exposed",
            "database",
            "unsecured",
            "misconfigured",
            "s3 bucket",
            "credential stuffing",
            "password hash",
            "salted",
            "plaintext password",
            "leak site",
            "dump",
            "dark web",
            "identity theft",
            "credit monitoring",
            "notification letter",
            "regulator fine",
            "gdpr",
            "ico fine",
            "class action",
            "settlement fund",
            "customer records",
            "social security number",
            "payment card",
            "pci",
            "tokenisation",
            "tokenization",
            "retention policy",
            "third party vendor",
            "processor",
            "controller",
            "disclosure delay",
            "material incident",
            "8 k filing",
            "consumer harm",
            "remediation",
            "audit finding",
            "encryption at rest",
        ),
        "wiki_topic": ("Data_breach", "Information_privacy", "Identity_theft"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Data breaches"]},
    },
    {
        "slug": "software-failures",
        "label": "Software failures",
        "family": "systems-and-security",
        "geo": "US",
        "lexicon": (
            "software",
            "bug",
            "defect",
            "regression",
            "race condition",
            "deadlock",
            "buffer overflow",
            "null pointer",
            "integer overflow",
            "off by one",
            "unit test",
            "integration test",
            "code review",
            "deployment",
            "rollback",
            "release",
            "hotfix",
            "legacy system",
            "migration",
            "cutover",
            "requirements",
            "specification",
            "formal verification",
            "post mortem",
            "root cause",
            "therac",
            "ariane",
            "knight capital",
            "trading algorithm",
            "flight software",
            "avionics",
            "control system",
            "firmware",
            "update",
            "compatibility",
            "edge case",
            "unhandled exception",
            "cascading failure",
            "technical debt",
            "incident review",
        ),
        "wiki_topic": ("Software_bug", "List_of_software_bugs", "Software_quality"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Software bugs"]},
    },
    {
        "slug": "power-grid-failures",
        "label": "Power grid failures",
        "family": "systems-and-security",
        "geo": "US",
        "lexicon": (
            "blackout",
            "outage",
            "grid",
            "power line",
            "transmission",
            "substation",
            "transformer",
            "circuit breaker",
            "relay",
            "protection scheme",
            "load shedding",
            "brownout",
            "cascading outage",
            "islanding",
            "frequency",
            "hertz",
            "voltage collapse",
            "reactive power",
            "generator",
            "turbine trip",
            "interconnection",
            "balancing authority",
            "reserve margin",
            "peak demand",
            "heat wave",
            "cold snap",
            "winterisation",
            "winterization",
            "vegetation management",
            "right of way",
            "sag",
            "arc",
            "wildfire ignition",
            "utility",
            "regulator",
            "nerc",
            "restoration",
            "black start",
            "customers",
            "dark",
        ),
        "wiki_topic": ("Power_outage", "Electrical_grid", "List_of_major_power_outages"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Power outages"]},
    },
    {
        "slug": "satellite-failures",
        "label": "Satellite and comms failures",
        "family": "systems-and-security",
        "geo": "US",
        "lexicon": (
            "satellite",
            "geostationary",
            "constellation",
            "transponder",
            "uplink",
            "downlink",
            "ground station",
            "telemetry",
            "attitude control",
            "reaction wheel",
            "gyroscope",
            "thruster",
            "station keeping",
            "solar array",
            "battery depletion",
            "radiation event",
            "single event upset",
            "debris",
            "collision avoidance",
            "deorbit",
            "graveyard orbit",
            "launch failure",
            "orbit insertion",
            "signal loss",
            "outage",
            "broadcast",
            "gps",
            "navigation",
            "timing signal",
            "undersea cable",
            "fibre cut",
            "fiber cut",
            "landing station",
            "network outage",
            "rerouting",
            "capacity",
            "operator",
            "insurance claim",
            "total loss",
            "anomaly report",
        ),
        "wiki_topic": ("Satellite", "Communications_satellite", "Space_debris"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Satellite failures"]},
    },
    {
        "slug": "automation-accidents",
        "label": "Automation and robot accidents",
        "family": "systems-and-security",
        "geo": "US",
        "lexicon": (
            "automation",
            "robot",
            "robotic",
            "autonomous",
            "self driving",
            "driverless",
            "autopilot",
            "advanced driver assistance",
            "lidar",
            "radar",
            "sensor fusion",
            "perception",
            "object detection",
            "false negative",
            "handover",
            "takeover request",
            "mode confusion",
            "automation surprise",
            "human factors",
            "operator complacency",
            "interlock",
            "light curtain",
            "safety cage",
            "emergency stop",
            "collaborative robot",
            "industrial robot",
            "assembly line",
            "warehouse robot",
            "agv",
            "machine vision",
            "training data",
            "edge case",
            "disengagement",
            "safety driver",
            "simulation",
            "validation",
            "certification",
            "regulator",
            "crash report",
            "uber atg",
        ),
        "wiki_topic": ("Self-driving_car", "Robot_safety", "Human_factors_and_ergonomics"),
        "wiki_event_pool": {"classes": [], "categories": ["Category:Self-driving car incidents"]},
    },
)


def families() -> dict[str, dict[str, tuple[str, ...]]]:
    """`family -> {slug: lexicon}`. The unit `lexicon.weights()` operates on."""
    out: dict[str, dict[str, tuple[str, ...]]] = {}
    for niche in BACKTEST_NICHES:
        out.setdefault(niche["family"], {})[niche["slug"]] = niche["lexicon"]
    return out


def backtest_weights() -> dict[str, dict[str, float]]:
    """`slug -> {term: weight}`, each family weighed against itself only.

    Never against the live family. Merging them re-weights the live lexicons —
    measured, `crash` falls from 1.00 to 0.032 — with no `LEXICON_VERSION` bump,
    because nobody would have edited a live lexicon (ADR-0026).
    """
    from nh.clustering.lexicon import weights

    computed: dict[str, dict[str, float]] = {}
    for lexicons in families().values():
        computed.update(weights(lexicons, BACKTEST_COMMON))
    return computed


def by_slug() -> dict[str, dict]:
    return {niche["slug"]: niche for niche in BACKTEST_NICHES}
